### PR TITLE
Change signature of dump_pretty

### PR DESCRIPTION
**Pull request by ergonjomeier**
After updating to 0.171.0, our code failed to compile with the following error:

`.../jsoncons/basic_json.hpp:3866:13: error: no matching member function for call to 'dump_pretty' dump_pretty(cont, options, indent, ec);`

The error occurs because on line 3866, dump_pretty is called with 4 parameters, but a dump_pretty function with the corresponding signature does not exists. After looking into the issue (and reading the doc https://github.com/danielaparker/jsoncons/blob/master/doc/ref/corelib/json/dump.md), I think that a dump_pretty function that takes an indent parameter should not exist at all.

I am not entirely sure how to fix this. The docs say that there should be a dump_pretty function that takes a CharContainer and options, with the options having a default parameter. My proposition changes the functions signature to fit the docs.

### CODE REVIEW

**Comment by danielaparker** [comment]
Thanks for fixing this!

**Comment by ergonjomeier** [comment]
Glad I could help :-)
