### ISSUE TITLE
Extra Qualification Error

### ISSUE THREAD

**Issue by lucaspcram** [danielaparker/jsoncons#43]
Hi Daniel,

EDIT: I rolled back to commit 7ce1d0 and it's working fine. So it could be an issue with one of your newer commits.

I have the jsoncons directory installed to my /usr/include folder. I'm getting errors when trying to compile using g++ version 4.9.3 with flag -std=c++14. The errors are below:

> /usr/include/jsoncons/json1.hpp:1696:14: error: extra qualification ‘jsoncons::basic_json<Char, Alloc>::’ on member ‘basic_json’ [-fpermissive]
     explicit basic_json<Char, Alloc>::basic_json()
              ^
/usr/include/jsoncons/json1.hpp:1696:50: error: explicit specialization of ‘jsoncons::basic_json<Char, Alloc>::basic_json()’ must be introduced by ‘template <>’
     explicit basic_json<Char, Alloc>::basic_json()

For reference, here is the program that will not compile:
test.cpp:

`#include <iostream>`
`#include <jsoncons/json.hpp>`

`int main(void)`
`{`
`         return 0;`
`}`

**Comment by danielaparker** [comment]
Thanks for reporting this! It should be fixed on master.

Daniel

**Comment by lucaspcram** [comment]
Working great!
