### ISSUE TITLE
Can not build tests with glibc >= 2.34 since version of catch2 is out of date

### ISSUE THREAD

**Issue by koeberlue** [danielaparker/jsoncons#389]
**Describe the bug**

# Expected behavior

Tests should build with `glibc >= 2.34`.

# Actual behavior

Tests do not build with `glibc >= 2.34`.

```
jsoncons/third_party/catch/catch.hpp:10791:58: error: call to non-‘constexpr’ function ‘long int sysconf(int)’
10791 |     static constexpr std::size_t sigStackSize = 32768 >= MINSIGSTKSZ ? 32768 : MINSIGSTKSZ;
      |                                                          ^~~~~~~~~~~
In file included from /usr/include/x86_64-linux-gnu/bits/sigstksz.h:24,
                 from /usr/include/signal.h:328,
                 from jsoncons/third_party/catch/catch.hpp:8007,
                 from jsoncons/test/src/main.cpp:2:

```

**Enumerate the steps to reproduce the bug**

On a machine with `glibc >= 2.34`:
```
mkdir build
cd build
cmake .. -DJSONCONS_BUILD_TESTS=On
cmake --build .
```

**Include a small, self-contained example if possible**

See above.

**What compiler, architecture, and operating system?**

- Compiler: clang-12
- Architecture (e.g. x86, x64): x64
- Operating system: Ubuntu 22.04.1

**What jsoncons library version?**

 - [ ] Latest release 0.168.5
 - [ ] Other release ______
 - [x] master
 
 # Possible solution
 
 It seems like issue comes from using Catch2. 
 
 https://github.com/catchorg/Catch2/issues/2421
 
This has been resolved some time ago, but we are currently using a pretty old version. Maybe it would be sufficient to just use the latest release of Catch2?
