### ISSUE TITLE
jsoncons build with GCC 10.2.0 fails without -Wno-deprecated-declarations compiler option

### ISSUE THREAD

**Issue by agritsiuk** [danielaparker/jsoncons#296]
Hello Daniel,

jsoncons build fails for us with GCC 10.2.0 if **-Wno-deprecated-declarations** compiler option is not added.

```
include/jsoncons/basic_json.hpp:4696:64: note: declared here
 4696 |     std::basic_string<char_type, char_traits_type, SAllocator> to_string(const basic_json_encode_options<char_type>& options,
      |                                                                ^~~~~~~~~
/export/home/scratch/ven_angritsiuk/plasma/build/Release/tools/TxnLogDump/jsoncons/src/JSONCONS_LIB/include/jsoncons/basic_json.hpp:4701:69: error: ‘std::__cxx11::basic_string<CharT, std::char_traits<_CharT>, SAllocator> jsoncons::basic_json<CharT, ImplementationPolicy, Allocator>::to_string(const jsoncons::basic_json_encode_options<CharT>&, const SAllocator&) const’ is deprecated: Instead, use dump(std::basic_ostream<char_type>&, const basic_json_encode_options<char_type>&) [-Werror=deprecated-declarations]
 4701 |         basic_compact_json_encoder<char_type, jsoncons::string_sink<string_type>> encoder(s, options);
```

Kind regards,
Andrei.

**Comment by danielaparker** [comment]
Are you using 
```c++
s = j.to_string(options);
```
in your code? This is a deprecated function, and should be replaced by

```c++
j.dump(s, options);
```

**Comment by agritsiuk** [comment]
Hi Daniel, just include of the header generates the warnings.

A build will fail with:
```
g++ -Werror -Iinclude main.cpp
```

main.cpp is:
```
#include <jsoncons/json.hpp>

int main()
{
    return 0;
}
```

**Comment by danielaparker** [comment]
Could you check if you still have issues compiling with the code on master?

**Comment by danielaparker** [comment]
That function has been removed in 0.160.0
